---
title: "CZZ Model Scan"
author: "HaoruiZhang"
date: "2024-11-12"
output: html_document
---

```{r}
rm(list = ls())
source('tools.r')
```

Step 1: Load Data
```{r}
Factors = readRDS('data/All_Factors_pool_standard.rds')
Rf = readRDS('data/Rf.rds')
Factors = as.data.frame(Factors)
Factors = Factors[,-1]
fnames = names(Factors)
print(fnames)
bench_fnames = c("Mkt", "SMB", "HML", "RMW", "CMA", "MOM", "ME", "IA", "ROE", "EG")
bench_Factors = Factors[,bench_fnames]
bench_Factors
```
Step 2: Get Length
```{r}
K = length(bench_fnames)
print(K)
```
Full Models
```{r}
thetam = CZZfactorg(xnames = bench_fnames, data = bench_Factors, trainpct = 0.15)
summaryczz(thetam)
```

```{r}
blout = CZZsummaryb(thetam, problower = .025, probupper = .975)
```

```{r}
bind = blout[,4] * blout[,5]
xlsig = fnames[bind > 0]
print(xlsig)
```

```{r}
scanls = CZZscang(data = bench_Factors, trainpct = 0.15)
```

```{r}
scanord = scanls$scanord

head(scanord, 10)
```
